name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the version # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sitapati/zbctl
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "${{ steps.get_version.outputs.VERSION }}, latest"
  tag-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: 'npm'
      - name: Install
        run: npm ci --ignore-scripts
#      - name: Run tests
#        run: npm run test
      - name: Build
        run: npm run build
      - name: Get the version # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set version
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version ${{ steps.get_version.outputs.VERSION }} -m "Publish v%s"
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public
      - name: Push changes
        run: git push --follow-tags